language: ruby
cache: bundler

before_install:
  - sudo apt-get install -y webp build-essential ffmpeg libopenjp2-7 libopenjp2-tools
  - wget https://www.imagemagick.org/download/ImageMagick.tar.gz
  - tar xf ImageMagick.tar.gz
  - cd ImageMagick-7*
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig /usr/local/lib
  - cd ..
  - rm -rf ImageMagick*
  - gem update --system
  - gem install bundler

script:
  - bundle exec rake test
  - bundle exec rake rubocop
